<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Authors>Rich Quackenbush</Authors>
		<Description>IP (TCP/UDP) Transport for NModbus.</Description>
		<IsPackable>true</IsPackable>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NModbus\NModbus.csproj" />
		<None Include="README.md" Pack="true" PackagePath="" />
	</ItemGroup>

</Project>
