<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Divergic.Logging.Xunit" Version="4.3.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageVersion Include="Neovolve.Logging.Xunit" Version="6.3.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="System.IO.Ports" Version="10.0.2" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>