<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<OutputType>exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Moq" />
		<PackageReference Include="Neovolve.Logging.Xunit.v3" />
		<PackageReference Include="Shouldly" />
		<PackageReference Include="xunit.v3.mtp-v2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\NModbus.Transport.IP\NModbus.Transport.IP.csproj" />
	</ItemGroup>

</Project>
