name: PR build

# https://futurestud.io/tutorials/github-actions-run-on-pull-request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore ./src/
      - name: Build
        run: dotnet build --configuration Release --no-restore ./src/
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            10.0.x
      - name: Test NModbus.BasicServer.Tests net10.0
        run: dotnet run --project NModbus.BasicServer.Tests\NModbus.BasicServer.Tests.csproj --framework net10.0
      - name: Test NModbus.BasicServer.Tests net9.0
        run: dotnet run --project NModbus.BasicServer.Tests\NModbus.BasicServer.Tests.csproj --framework net9.0
      - name: Test NModbus.BasicServer.Tests net8.0
        run: dotnet run --project NModbus.BasicServer.Tests\NModbus.BasicServer.Tests.csproj --framework net8.0
    

      # Do a pack (we don't care about the version because we're just going to throw it away)
      # just to make sure the solution is packable. It's unfortunate to make it to a post PR 
      # build to find out that we can't pack.
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=1.0.0 --output . ./src/